.travis.yml
pom.xml

* Extract secrets only for non-PRs
* Remove obsolete plugin, as we are using maven-release-plugin (see http://www.sonatype.org/nexus/2015/06/02/how-to-publish-software-artifacts-to-maven-central/)
* Using single release profile instead of separate profiles from old config

Fixing PR builds

---

README.md
api/src/main/java/com/spotify/spydra/api/DataprocAPI.java
common/src/main/java/com/spotify/spydra/util/SpydraArgumentUtil.java
metrics/src/main/java/com/spotify/spydra/metrics/Metrics.java
metrics/src/main/java/com/spotify/spydra/metrics/impl/LoggingMetrics.java

Using this new metric we can better follow where the Dataproc clusters get created in. I cleaned up also the configuration overwriting functionality, as I had hard time following it, causing me some extra wasted time effort.

Add zone metric for create cluster

---

README.md
common/src/main/java/com/spotify/spydra/util/SpydraArgumentUtil.java
spydra/src/main/java/com/spotify/spydra/submitter/runner/Runner.java

Not using a service account credential (silently) breaks all
the rest of Spydra.

Always require a userId

---

api/src/main/java/com/spotify/spydra/api/model/Cluster.java
spydra/src/main/java/com/spotify/spydra/submitter/api/PoolingSubmitter.java
spydra/src/test/java/com/spotify/spydra/submitter/api/PoolingTest.java

This implementation looks at the initial heartbeat set during cluster
creation. Hearbeat on the cluster is not updated and should not be used
for such a check. A proper check would look at the master node for each
cluster.
For now, we'll accept the small window where we could select a cluster
while it has already decided to self-destruct but it has not yet updated
it's state to `DELETING` yet. This transition usually is visible within
seconds from submitting a deletion.

Remove PoolingSubmitter.Conditions.heartIsBeating

---

README.md

Although not wrong, definitely confusing those looking for environment variables in the code base.

Clarify HADOOP_USER_NAME for dump-logs command

---

api/src/main/java/com/spotify/spydra/api/DataprocAPI.java
api/src/main/java/com/spotify/spydra/api/gcloud/GcloudExecutor.java
common/src/main/java/com/spotify/spydra/util/GcpUtils.java
common/src/main/java/com/spotify/spydra/util/SpydraArgumentUtil.java
spydra/src/main/java/com/spotify/spydra/submitter/api/DynamicSubmitter.java
spydra/src/main/java/com/spotify/spydra/submitter/api/PoolingSubmitter.java
spydra/src/main/java/com/spotify/spydra/submitter/api/Submitter.java
spydra/src/main/java/com/spotify/spydra/submitter/executor/DataprocExecutor.java
spydra/src/main/java/com/spotify/spydra/submitter/runner/Runner.java
spydra/src/test/java/com/spotify/spydra/LifecycleIT.java

Using account parameter with gcloud command locally makes spydra use the provided credential for the spydra command, and not the default from gcloud session outside spydra.

Add account gcloud parameter

---

spydra/src/main/resources/spydra_config_schema.json

Is a string (java.time.duration), not boolean.

Fix type of pooling max_age

---

spydra/src/main/resources/dataproc_defaults.json

As a good practice to optimize network and storage usage I propose to enable compression by default in map-reduce applications.

Enable MR intermediate and fileoutput compression by default

---

spydra/src/main/java/com/spotify/spydra/submitter/api/DynamicSubmitter.java
spydra/src/test/java/com/spotify/spydra/submitter/api/PoolingTest.java

The aim of this PR is to solve the exception `java.util.NoSuchElementException: No value present` thrown when a new job is submitted to a cluster that has been previously created (using pooling). In that case, the cluster name has not been set and consequently the check of the cluster name in `releaseCluster` fails.
See trace below:
```
Exception in thread "main" java.util.NoSuchElementException: No value present
at java.util.Optional.get(Optional.java:135)
at com.spotify.spydra.model.SpydraArgument$Cluster.getName(SpydraArgument.java:90)
at com.spotify.spydra.submitter.api.PoolingSubmitter.lambda$releaseCluster$1(PoolingSubmitter.java:112)
at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:95 …
```

Fix undefined name in releaseCluster

---

spydra/src/main/java/com/spotify/spydra/submitter/api/PoolingSubmitter.java

This significantly reduces the time for the limit to stabilize after
fluctuations due to multiple actors racing to create clusters

Sort and limit poolable clusters

---

api/src/main/java/com/spotify/spydra/api/DataprocAPI.java
api/src/main/java/com/spotify/spydra/api/gcloud/GcloudExecutor.java
api/src/main/java/com/spotify/spydra/api/model/Cluster.java
common/src/main/java/com/spotify/spydra/model/SpydraArgument.java
spydra/src/main/java/com/spotify/spydra/submitter/api/DynamicSubmitter.java
spydra/src/main/java/com/spotify/spydra/submitter/api/PoolingSubmitter.java
spydra/src/test/java/com/spotify/spydra/submitter/api/PoolingTest.java

This PR is to fix #48 
PoolingSubmitter looks at all clusters in a project, this should be segmented on a user provided value allowing multiple pools to coexist in a single project.

Fix pooling #48

---

api/src/main/java/com/spotify/spydra/api/gcloud/GcloudExecutor.java
api/src/main/java/com/spotify/spydra/api/process/ProcessHelper.java
spydra/src/main/java/com/spotify/spydra/submitter/api/DynamicSubmitter.java
spydra/src/main/java/com/spotify/spydra/submitter/executor/OnPremiseExecutor.java

This PR changes the gcloud execution to parse the output of the command based on the exit code. On error cases the stderr is read and logged, while on success case the output is parsed as JSON and returned. This will improve Spydra metrics as not all failures will be reported now as JSON parsing exceptions, which become fatal errors. After this PR is merged, the fatal errors due to gcloud command failing will become execution failures, like cluster creation or listing failure, instead.
Reading of the stderr leaves a door open for future to base our error metrics to actually parse the failure and report different types of errors. This PR will not add more error events yet.

Make gcloud errors non-fatal

---

api/src/main/java/com/spotify/spydra/api/DataprocAPI.java
api/src/main/java/com/spotify/spydra/api/gcloud/GcloudExecutor.java
common/src/main/java/com/spotify/spydra/model/SpydraArgument.java
metrics/src/main/java/com/spotify/spydra/metrics/Metrics.java
metrics/src/main/java/com/spotify/spydra/metrics/impl/LoggingMetrics.java
spydra/init-actions/self-destruct.py
spydra/src/main/java/com/spotify/spydra/submitter/api/DynamicSubmitter.java
spydra/src/main/java/com/spotify/spydra/submitter/api/PoolingSubmitter.java

this PR solves #60 by moving heartbeat information from instance level metadata (which is set and updated on the master node instance and not updated for workers) to project level metadata which is shared and available for all instances within the cluster.

Move heartbeat metadata to project level

---

spydra/pom.xml

This changes the GCS batch request endpoint to the new per-api endpoint
(https://github.com/GoogleCloudPlatform/bigdata-interop/blob/branch-1.6.x/gcs/CHANGES.txt),
as the old endpoint is being deprecated
(https://developers.googleblog.com/2018/03/discontinuing-support-for-json-rpc-and.html).

Update GCS connector from 1.6.0 to 1.6.3.

---

spydra/src/main/java/com/spotify/spydra/submitter/api/ClusterPlacement.java
spydra/src/main/java/com/spotify/spydra/submitter/api/PoolingSubmitter.java
spydra/src/test/java/com/spotify/spydra/submitter/api/ClusterPlacementTest.java
spydra/src/test/java/com/spotify/spydra/submitter/api/PoolingTest.java

This adds an offset to the formula that computes the generation. This is a random value between 0 and the max age of the cluster. The value is generated using the number of the cluster as seed to make it deterministic.
Adding this offset alleviates the situation where all the clusters of a generation are created at the same time having for some time twice the maximum number of clusters.

Add random offset to generation calculation

---

api/src/main/java/com/spotify/spydra/api/process/ProcessHelper.java
spydra/src/test/java/com/spotify/spydra/api/process/ProcessHelperTest.java

Spydra uses a built-in `ProcessHelper` class to shell out to command line tools, like `gcloud`. This helper waits for the subprocess to exit before reading its output, which can lead to deadlock if the process generates more than 64kb<sup>1</sup> of output on `stdout` or `stderr`.
This PR fixes this issue by:
- reading from both `stdout` and `stderr` of the process while waiting for it to complete
- buffering the output of both streams into two independent `StringBuilder` objects
- adding a test for this behaviour (although this test requires the test runner to shell out to `bash`)
---
<sup>1</sup> this is [the default size of the pipe buffer](https://unix.stackexchange.com/questions/11946/how-big-is-the-pipe-buffer) on Linux, although this can vary across systems.

Read from streams in ProcessHelper to avoid deadlock on large output.

---

spydra/src/main/resources/dataproc_defaults.json

Change property name from `fs.gs.implicit.directory.repair` to `fs.gs.implicit.dir.repair.enable`.
Valid configuration value could be seen [here](https://github.com/GoogleCloudPlatform/bigdata-interop/blob/9e572ec40f2ec6df1144963a9b5ca4e6052e5b4d/gcs/src/main/java/com/google/cloud/hadoop/fs/gcs/GoogleHadoopFileSystemConfiguration.java#L276:L279).

Fix GCS connector property name.

---

.travis.yml

The CI build currently fails during installation of Oracle JDK, see details below:
```
$ ~/bin/install-jdk.sh --target "/home/travis/oraclejdk8" --workspace "/home/travis/.cache/install-jdk" --feature "8" --license "BCL"
Ignoring license option: BCL -- using GPLv2+CE by default
install-jdk.sh 2020-06-02
Expected feature release number in range of 9 to 16, but got: 8
The command "~/bin/install-jdk.sh --target "/home/travis/oraclejdk8" --workspace "/home/travis/.cache/install-jdk" --feature "8" --license "BCL"" failed and exited with 3 during .
Your build has been stopped.
```
This is likely related to the Ubuntu distro used in the build task, see discussions [here](https://travis-ci.community/t/error-installing-oraclejdk8-expected-feature-release-number-in-range-of-9-to-14-but-got-8/3766/5) …

Set Ubuntu distro for build task

---

spydra/src/test/java/com/spotify/spydra/LifecycleIT.java

The check that determines if integration tests should be skipped involves a check on whether it's running on compute engine and if `GOOGLE_APPLICATION_CREDENTIALS` is set. The first check succeeds with the result that integration tests are run when `GOOGLE_APPLICATION_CREDENTIALS` is not set, resulting in the failure:
```
ERROR [main] (GcloudExecutor.java:77) - ERROR: (gcloud.beta.dataproc.clusters.create) You do not currently have an active account selected.
Please run:
$ gcloud auth login
to obtain new credentials, or if you have already logged in with a
different account:
$ gcloud config set account ACCOUNT
to select an already authenticated account to use.
```
This change skips integration tests when `GOOGLE_APPLICATION_CREDENTIALS` is missing. See last [successful build …

Skip integration tests when GOOGLE_APPLICATION_CREDENTIALS is not set

---

spydra/pom.xml

This puts commons-cli with version defined by the spydra-parent as transitive dependency.
When letting maven resolve for sydra, common-cli 1.2 was taken from hadoop transitive dependency.

Set explicitly commons-cli dependency
